# Generated by Django 4.2.7 on 2023-12-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField(default='none', max_length=250)),
                ('description', models.TextField()),
                ('img1', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='project/images/')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='project/images/')),
            ],
        ),
    ]
