# Generated by Django 4.2.7 on 2023-12-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amking_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
    ]
