# Generated by Django 4.2.7 on 2023-12-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('years', models.IntegerField()),
                ('awards', models.IntegerField()),
            ],
        ),
    ]
