# Generated by Django 4.2.7 on 2023-12-19 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='success',
            options={'verbose_name': 'Pages'},
        ),
    ]
