# Generated by Django 4.2.7 on 2023-12-19 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_success_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='success',
            options={'verbose_name_plural': 'Success'},
        ),
    ]
