# Generated by Django 4.2.7 on 2024-01-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(null=True, upload_to='testimonials/images/'),
        ),
    ]
